;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; STM8_TEL 
;; Tiny Embedded Language 
;; created in smallForth 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

: BAD ABORT" BAD SYNTAX" ; 

: NUMBER TOKEN NUMBER? ~IF BAD THEN ;

: FACTOR TOKEN DUP C@ IF 'EVAL 
: OP  ' ;

: EXPR NUMBER OP NUMBER SWAP EXECUTE ;

: CONST NUMBER CONSTANT ; 

: VAR VARIABLE ;

: := EVAL SWAP ! ; 

\ arithmetic 

: + NUMBER NUMBER + ;

: - NUMBER NUMBER - ;

: * NUMBER NUMBER * ;

: / NUMBER NUMBER / ;

: % NUMBER NUMBER MOD ;

: REPEAT NUMBER 1- [COMPILE] FOR ; COMPILE-ONLY IMMEDIATE

: {  BEGIN ; COMPILE-ONLY IMMEDIATE 

: }  REPEAT ; COMPILE-ONLY IMMEDIATE 

: CHAR TOKEN DUP C@ IF 1+ C@ ELSE BAD THEN ;

: [CHAR] CHAR [COMPILE] LITERAL ; IMMEDIATE COMPILE-ONLY 

: [BYTE] TOKEN NUMBER? IF C, ELSE BAD THEN ; IMMEDIATE COMPILE-ONLY 

: [WORD] TOKEN NUMBER? IF , ELSE BAD THEN ; IMMEDIATE COMPILE-ONLY 

: :VAR  ( a -- a f )
    DUP 1+ C@ [CHAR] : = IF -1 ELSE 0 THEN ;

: ARGV  
    TOKEN :VAR IF COUNT 1- OVER C! 'EVAL @EXECUTE @
    ELSE 'EVAL @EXECUTE THEN 
;

 


